### ISSUE TITLE
I can't find the scraping code for https://poetry.dctabudhabi.ae

### ISSUE THREAD

**Issue by AliOsm** [hci-lab/LearningMetersPoems#2]
Hello team,

I want to check if you can add the scraping code for the https://poetry.dctabudhabi.ae website.

Thanks!

**Comment by moroclash** [comment]
Hello @AliOsm, actually you can reach the Dataset we have used through that [URL](https://hci-lab.github.io/LearningMetersPoems/), and regarding the scarping code, it is out of date and useless now because the website you mentioned had changed its UI entirely, so writing new scraper is mandatory.

**Comment by AliOsm** [comment]
Hello @moroclash , we already started a new project to collect poetry data. You can contribute on this repo: https://github.com/ARBML/tnqeeb.
